---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.25"
        name: phpmyadmin
        ports:
        - containerPort: 80
        env:
        - name: PMA_USER
          value: "netology"
        - name: PMA_PASSWORD
          value: ""
        - name: PMA_HOST
          value: "rc1a-khit577op6wmp8k1.mdb.yandexcloud.net"

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80