---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 75%
  selector:
    matchLabels:
      app: app-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.28
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        ports:
        - containerPort: 8080
...
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  selector:
    app: app-deployment
  ports:
    - name: nginx-port
      port: 80
      targetPort: 80
    - name: multitool-port
      port: 8080
      targetPort: 8080
...
